project:
  type: website
  output-dir: _site

website:
  title: "MICB 323: Molecular Immunology & Virology Laboratory"
  description: "MOLECULAR IMMUNOLOGY & VIROLOGY LABORATORY"
  site-url: https://ubc-micb-323.github.io/2025WT2
  navbar:
    left:
      - overview.qmd
      - evaluation.qmd
      - course_policies.qmd
      - schedule.qmd
    right:
      - text: "Dowdload as PDF"
        href: MICB323-2025WT2-Syllabus.pdf
      - icon: github
        href: https://github.com/ubc-micb-323/2025WT2

format:
  html:
    theme:
      light: 
        - Lumen
        - assets/theme.scss
      dark:
        - cosmo
        - assets/theme.scss 
      
    toc: true
    toc-depth: 3
    number-sections: false
    link-external-icon: true
    link-external-newwindow: true

execute:
  freeze: auto
